version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:

  pre_build:
    commands:
  build:
    commands:

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'

cache:
  paths:
    - node_modules/
